### ISSUE TITLE
Modifing your Version to another Hotend

### ISSUE THREAD

**Issue by Hates1209** [strayr/Ender3_switchwire_fixes#1]
Sorry wrong repo

**Comment by Hates1209** [comment]
![IMG_5164](https://user-images.githubusercontent.com/93094716/229231397-c7f84ad6-c4a5-493d-8ee8-81d6938e72ec.jpeg)
![IMG_5165](https://user-images.githubusercontent.com/93094716/229231431-19b11175-de8f-4957-a1fa-0f2464929e1f.jpeg)
![IMG_5163](https://user-images.githubusercontent.com/93094716/229231446-d8ad6c22-ef06-48d4-bb6c-bc47b77522e9.jpeg)

**Comment by strayr** [comment]
Check the dimensions shown. The tip of the nozzle must be 61.50mm from the
reference plane at the top of the toolhead.

It may help to start with a more open toolhead, I can't remember if I
started with a dragon or a v6 hotend toolhead but it's in the fusion 360
timeline what I did.
